### ISSUE TITLE
Add grain removal based on height (identify and isolate scars)

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#154]
**Is your feature request related to a problem? Please describe.**
Removing anomalously high-up grains would be useful as it would remove artefacts such as scars and blobs that are not wanted and would mess with the scaling of the data.

**Describe the solution you'd like**
A system that detects grains that are 2 standard deviations from the mean grain height and removes them.

**Comment by SylviaWhittle** [comment]
This maybe should go in filters as it could help with flattening

**Comment by SylviaWhittle** [comment]
Focus on scars as opposed to blobs

**Comment by bobturneruk** [comment]
See http://gwyddion.net/documentation/user-guide-en/scan-line-defects.html

**Comment by ns-rse** [comment]
I don't know if this would be of use but I realised I had previously created #202 because I'd stumbled across the [Hough Transform](https://en.wikipedia.org/wiki/Hough_transform) which is a method for identifying classes of shapes, classically straight-lines, from images.

There are methods in scikit-image that implement this (see #202 for links).

**Comment by alicepyne** [comment]
Would be good to have options for how many SD in the config file? In the case of including e.g. proteins which are 10x the height of DNA.
