### ISSUE TITLE
Optional plotting of individual grains.

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#205]
**Is your feature request related to a problem? Please describe.**

Currently individual grains are plotted (x4 images per grain) automatically when calculating grain statistics. This should be optional.

**Describe the solution you'd like**

See above.

**Describe alternatives you've considered**
N/A

**Comment by MaxGamill-Sheffield** [comment]
The `grainstats.saved_cropped_grains: False` option in the config can remove all grain plots. Additionally, if one only wants the cropped grain image (not the mask or mask-image hybrid), they can use `plotting.image_set: core`.

While now optional, this should be moved to be plotted outside of grainstats, the only reason for doing so is because this is where the bounding boxes are obtained and thus would require more refactoring of `grains.py` (where I think these plots should be)
