### ISSUE TITLE
Problem in description

### ISSUE THREAD

**Issue by asal9122** [AFM-SPM/TopoStats#213]
In the decription This address should be changed:
docker run -it -v <path/to/your/topostats>:/home/TopoStats afmspm/topostats:wip

to: 

docker run -it -v "C:\Users\...\TopoStats-master":/home/TopoStats afmspm/topostats:wip

Double quotation works but not with < or single quotation.

**Comment by SylviaWhittle** [comment]
Thanks for the feedback! 

The `<` `>` there are not intended to be kept, they were an attempt to show that their contents are a placeholder for a path that will be unique to your system. Sorry this is not clear.

The trouble with using `C:\Users...\TopoStats-master` is that not everyone is using a Windows system, so we are trying to keep it generic for all operating systems. 


What do you think about using this line instead? 

`docker run -it -v path_to_your_topostats:/home/TopoStats afmspm/topostats:wip`

Do you think it's clear that the user should replace the `path_to_your_topostats` with a file path for their system?

**Comment by ns-rse** [comment]
Hi Zahra/@ashal9122,

Thanks for the feedback it is always appreciated.

TopoStats has been undergoing heavy revision and work of late and one of the major changes is removing the need to use Docker completely (its required to interface with Gwyddion using Python 2.7 because this version of Python reached its [end of life 2020-01-01](https://endoflife.date/python) and is no longer supported).

Thus most of the teams effort has been focused on removing this dependency and we are not far off releasing an initial version of TopoStats that no longer depends on Gwyddion and instead runs purely in Python >= 3.8 and uses [scikit-image](https://scikit-image.org/).

It was unfortunate that we hadn't finished this work in time for the work shop you attended recently.

If you want to try this out before it is released then you can do so on the `dev` branch. Any feedback you have would be very useful.

Thanks again,

Neil

**Comment by ns-rse** [comment]
Closing as we have now [released TopoStats 2.0.0](https://github.com/AFM-SPM/TopoStats/releases/tag/v2.0.0) and won't be further developing old TopoStats (although it remains available on the [legacy branch](https://github.com/AFM-SPM/TopoStats/tree/legacy)).

But please do try the new TopoStats, we are keen to get feedback from users.
