### ISSUE TITLE
dntracing to use bounded grains from GrainStats

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#294]
Currently dnatracing takes the labelled image and extracts each identified molecule but then works with the whole 1000x1000 pixel image. It would be (marginally) faster and make more sense if instead dnatracing worked with cropped images.

We already have existing code that does this in `topostats/grainstats.py` as lines 162-276 loops over all grains (`region_properties`) and crops them before plotting and calculating statistics.

To this end rather than duplicate code we can modify `grainstats/GrainStats` class as described in #295

**Comment by MaxGamill-Sheffield** [comment]
Update on this issue, while refactoring dnatracing.py, I've seen that the only reason we process grain-by-grain is due to a dilation step. I'm hoping that this step is the source of some poor tracing issues and that if it can be removed, the skeletonisation and pruning steps to follow can be done across the whole image (currently this would save about 0.8s on minicircles.spm).

After, I believe all the current statistics outputs use the list of points produced by the traces for their calculations.

This means that bounded grains may not need to be used at all.

**Comment by MaxGamill-Sheffield** [comment]
I also see that many of the subsequent steps in dnatracing require the functions to not "hit the edges". This means that we'd need to think about making the bounding boxes bigger for input here.
