### ISSUE TITLE
Images saved to wrong place & Processed dir error

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#428]
**Describe the bug**
No matter where the output_dir is set, all images go into a `./Processed` folder that is made instead of `./<output_dir>/Processed`. This is an issue because the "`older_statistics.csv` file does want to go into the latter, throwing an error when this dir doesn't exist.

**To Reproduce**
Run topostats (main branch)
See "Processed" directory in `.`
Error thrown due to missing 

**Expected behavior**
Processed folder should be in "./<output_dir>"

**Output**
Something along the lines of :
`OSError: "Processed"  directory not found`

**Additional context**
FIX:
Remove the `.parent` on line 173 -> ` _output_dir = get_out_path(image_path, base_dir, output_dir) / "Processed"`

**Comment by slackline** [comment]
Strange, that `.parent` call hasn't changed in five months since you implemented it, can't think why it would suddenly break. :thinking:

**Comment by MaxGamill-Sheffield** [comment]
Same, and I'm guessing it's the same for the function beneath it too

**Comment by ns-rse** [comment]
Apologies commented from the wrong browser where I am logged into my personal GitHub account.

One thought is perhaps related to OS, is this happening on Windows or across all tested platforms?

Directory creation is currently a bit messy I feel. I'd started with a user specified `output_dir` and then a sub-directory for each image. The introduction of images and making the distinction of `processed` introduced another layer as did splitting images into `filter` and `grains` and then a further layer with `upper` and `lower`.

Perhaps taking a step back and reviewing what is essential and the simplest structure we can deduce might be appropriate rather than putting a plaster on this.

**Comment by Jean-Du** [comment]
I believe this is caused by periods in the file name. 
In `get_out_path` in `utils.py`, lines 100-111 treat image paths with suffixes differently from those without suffixes, and the parent directory is used for the former case. For images with periods in their names, the part after the period is for some reason wrongly treated as a suffix, causing the creating of `processed` in the wrong place.
There are two ways to prove such is the case:
1. Remove all periods from the file name, and the `processed` folder should be in the right place
2. For a file that does contain periods, remove the `parent` part from lines 104 and/or 109 in `utils.py`, and the `processed` folder should be in the right place

**Comment by SylviaWhittle** [comment]
I tried this PR out on my system with a variety of different folder setups, and it seems to do as @ns-rse says. It does not fix the double periods issue (though this PR isn't intending to AFAIK - I checked just in case and to clarify), so that still needs a PR after this one.

Here is an example of the file structure, could someone verify if this is intended? Looks good to me.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/86117496/211678254-a876e75f-02c6-43db-908e-24186b0b3232.png">
