### ISSUE TITLE
Splining Linear Molecules

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#607]
@Jean-Du has done some work on the [JeanDu/Spline-linear-molecules](https://github.com/AFM-SPM/TopoStats/tree/JeanDu/Spline-linear-molecules) for splining of linear molecules which currently isn't in the `main` branch.

This needs incorporating along with tests.

**Comment by MaxGamill-Sheffield** [comment]
I've pulled some of @Jean-Du code across for more accurate contour lengths. Just noting an issue I've seen which should be covered by the tests:

Very sharp bends can cause the traces to exceed the limits of the image (see below). Jean's suggestions are outlined below:

"This should be because during the 'get fitted traces' step, sometimes the fitting produces points that are far from the backbone; you can try fixing this by:
1. Feed the ordered traces to the splining function, instead of the fitted traces, just for that image
2. Further increase the smoothness"
![26-ordered-traces](https://github.com/AFM-SPM/TopoStats/assets/91465918/e8f5e1fe-ada9-45cd-870d-16f6ac88148a)
![27-fitted-traces](https://github.com/AFM-SPM/TopoStats/assets/91465918/4c7313ab-52ea-4270-8398-a48f0c67c3f5)
![28-splined-traces](https://github.com/AFM-SPM/TopoStats/assets/91465918/f6025ca9-e8cd-4c80-8d3c-2748d3d2faf9)
