### ISSUE TITLE
Remove broad Exception catch surrounding dnatracing

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#699]
Currently, we have a broad `try` `except` clause catching any and all `Exceptions`. This caused me to not notice dnatracing failing despite having a test for it, and allowing #696 to slip under our radars. (Clearly also the fault of me not writing a very good test! Succeeding even when the expected output was not complete). I think it is in our best interests to tighten this exception to only allow specific, known exceptions, which might prevent things like this going forward.

Thoughts @ns-rse ?

**Comment by ns-rse** [comment]
I was trying to include more `try: ... except: ...` in the refactoring of `dnatracing`. There is still a lot of code in there that needs refactoring though (e.g. pruning skeletons is pending as progress on incorporating iterative pruning routines up-stream to `skan` has not progressed as fast as we might have hoped due to annual leave and illness).

Removing the broad exception is definitely something that should be done though. It was put on because there was the desire for things to fail gracefully and errors on one image not to prevent all other images from being processed.
